// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChanxOB4ePu35CJjx9gUeH3qHag-Omuu8',
    appId: '1:566372360464:web:721501f865710d56230595',
    messagingSenderId: '566372360464',
    projectId: 'expense-tesis',
    authDomain: 'expense-tesis.firebaseapp.com',
    storageBucket: 'expense-tesis.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMeLG-TokGrPHP_Tv2emSy2eUylElMypk',
    appId: '1:566372360464:android:8ec6a79799e522cd230595',
    messagingSenderId: '566372360464',
    projectId: 'expense-tesis',
    storageBucket: 'expense-tesis.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5J-V9ZK8TeogU84s2ZN2FpB5IjoQCTc0',
    appId: '1:566372360464:ios:f4fcee60b164596e230595',
    messagingSenderId: '566372360464',
    projectId: 'expense-tesis',
    storageBucket: 'expense-tesis.firebasestorage.app',
    iosBundleId: 'com.example.expensesTrackerProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5J-V9ZK8TeogU84s2ZN2FpB5IjoQCTc0',
    appId: '1:566372360464:ios:f4fcee60b164596e230595',
    messagingSenderId: '566372360464',
    projectId: 'expense-tesis',
    storageBucket: 'expense-tesis.firebasestorage.app',
    iosBundleId: 'com.example.expensesTrackerProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChanxOB4ePu35CJjx9gUeH3qHag-Omuu8',
    appId: '1:566372360464:web:7ab7f615609db41e230595',
    messagingSenderId: '566372360464',
    projectId: 'expense-tesis',
    authDomain: 'expense-tesis.firebaseapp.com',
    storageBucket: 'expense-tesis.firebasestorage.app',
  );
}
